# fly.toml app configuration file generated for project-server on 2024-05-17T10:44:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'project-server'
primary_region = 'mad'

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
